In [7]:
!pip install yfinance

Collecting yfinance
  Obtaining dependency information for yfinance from https://files.pythonhosted.org/packages/a2/1d/1a35edd6943f27ff4b5e2d6ba634e7d1bac2e6f815f8efae0666ac71a68d/yfinance-0.2.46-py2.py3-none-any.whl.metadata
  Downloading yfinance-0.2.46-py2.py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: pandas>=1.3.0 in c:\users\mayan\anaconda3\lib\site-packages (from yfinance) (2.0.3)
Requirement already satisfied: numpy>=1.16.5 in c:\users\mayan\anaconda3\lib\site-packages (from yfinance) (1.24.3)
Requirement already satisfied: requests>=2.31 in c:\users\mayan\anaconda3\lib\site-packages (from yfinance) (2.31.0)
Collecting multitasking>=0.0.7 (from yfinance)
  Obtaining dependency information for multitasking>=0.0.7 from https://files.pythonhosted.org/packages/3e/8a/bb3160e76e844db9e69a413f055818969c8acade64e1a9ac5ce9dfdcf6c1/multitasking-0.0.11-py3-none-any.whl.metadata
  Downloading multitasking-0.0.11-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: lxml>=4.9.1 in c:\users\mayan\anaconda3\lib\site-packages (from yfinance) (4.9.3)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\mayan\anaconda3\lib\site-packages (from yfinance) (3.10.0)
Requirement already satisfied: pytz>=2022.5 in c:\users\mayan\anaconda3\lib\site-packages (from yfinance) (2023.3.post1)
Collecting frozendict>=2.3.4 (from yfinance)
  Obtaining dependency information for frozendict>=2.3.4 from https://files.pythonhosted.org/packages/04/13/d9839089b900fa7b479cce495d62110cddc4bd5630a04d8469916c0e79c5/frozendict-2.4.6-py311-none-any.whl.metadata
  Downloading frozendict-2.4.6-py311-none-any.whl.metadata (23 kB)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-3.17.7.tar.gz (939 kB)
     ---------------------------------------- 0.0/939.5 kB ? eta -:--:--
     ------ ------------------------------- 163.8/939.5 kB 4.8 MB/s eta 0:00:01
     ------------------------------------- 939.5/939.5 kB 11.9 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\mayan\anaconda3\lib\site-packages (from yfinance) (4.12.2)
Collecting html5lib>=1.1 (from yfinance)
  Obtaining dependency information for html5lib>=1.1 from https://files.pythonhosted.org/packages/6c/dd/a834df6482147d48e225a49515aabc28974ad5a4ca3215c18a882565b028/html5lib-1.1-py2.py3-none-any.whl.metadata
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: soupsieve>1.2 in c:\users\mayan\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.4)
Requirement already satisfied: six>=1.9 in c:\users\mayan\anaconda3\lib\site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in c:\users\mayan\anaconda3\lib\site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mayan\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in c:\users\mayan\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\mayan\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mayan\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mayan\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mayan\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2023.11.17)
Downloading yfinance-0.2.46-py2.py3-none-any.whl (100 kB)
   ---------------------------------------- 0.0/101.0 kB ? eta -:--:--
   ---------------------------------------- 101.0/101.0 kB 6.0 MB/s eta 0:00:00
Downloading frozendict-2.4.6-py311-none-any.whl (16 kB)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
   ---------------------------------------- 0.0/112.2 kB ? eta -:--:--
   ---------------------------------------- 112.2/112.2 kB ? eta 0:00:00
Downloading multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Building wheels for collected packages: peewee
  Building wheel for peewee (pyproject.toml): started
  Building wheel for peewee (pyproject.toml): finished with status 'done'
  Created wheel for peewee: filename=peewee-3.17.7-py3-none-any.whl size=138951 sha256=f74b5a4d46d9e00414434f1491db341bb4bb44e9ecebc6c43f79250f17c5c44b
  Stored in directory: c:\users\mayan\appdata\local\pip\cache\wheels\fd\28\34\9ba1363b76703fe35ae8296af28ea74578a41b83544bb9da65
Successfully built peewee
Installing collected packages: peewee, multitasking, html5lib, frozendict, yfinance
Successfully installed frozendict-2.4.6 html5lib-1.1 multitasking-0.0.11 peewee-3.17.7 yfinance-0.2.46

In [1]:
import pandas_datareader.data as web
import pandas as pd
import datetime as dt
import yfinance as yf

In [2]:
start = '2014'
end = dt.datetime(2017, 5, 24)
ticker = yf.Ticker('ABBOTINDIA.NS')
data = ticker.history(period='5d',
                      interval='1m',
                      start=None,
                      end=None,
                      actions=True,
                      auto_adjust=True,
                      back_adjust=False)
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1272 entries, 2024-10-29 09:15:00+05:30 to 2024-11-04 15:29:00+05:30
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          1272 non-null   float64
 1   High          1272 non-null   float64
 2   Low           1272 non-null   float64
 3   Close         1272 non-null   float64
 4   Volume        1272 non-null   int64
 5   Dividends     1272 non-null   float64
 6   Stock Splits  1272 non-null   float64
dtypes: float64(6), int64(1)
memory usage: 79.5 KB

In [3]:
data['wts'] = 1

In [4]:
data

,Open,High,Low,Close,Volume,Dividends,Stock Splits,wts
Datetime,,,,,,,,
2024-10-29 09:15:00+05:30,28400.000000,28400.000000,28369.849609,28369.849609,0,0.0,0.0,1
2024-10-29 09:16:00+05:30,28369.849609,28369.849609,28312.449219,28312.449219,4,0.0,0.0,1
2024-10-29 09:17:00+05:30,28300.099609,28300.099609,28250.349609,28250.349609,56,0.0,0.0,1
2024-10-29 09:18:00+05:30,28280.000000,28300.000000,28276.750000,28300.000000,12,0.0,0.0,1
2024-10-29 09:19:00+05:30,28302.250000,28375.900391,28302.250000,28375.900391,7,0.0,0.0,1
...,...,...,...,...,...,...,...,...
2024-11-04 15:25:00+05:30,29488.000000,29500.000000,29469.300781,29500.000000,150,0.0,0.0,1
2024-11-04 15:26:00+05:30,29501.599609,29548.800781,29500.000000,29548.800781,236,0.0,0.0,1
2024-11-04 15:27:00+05:30,29549.449219,29575.300781,29549.449219,29575.000000,160,0.0,0.0,1
2024-11-04 15:28:00+05:30,29580.000000,29649.900391,29550.000000,29636.250000,250,0.0,0.0,1
2024-11-04 15:29:00+05:30,29572.500000,29650.000000,29460.449219,29460.449219,78,0.0,0.0,1

In [5]:
symbls = []
symbls.append(data['Open'].values)

In [6]:
sum(data['Open'])

36424178.537109375

In [10]:
trent = yf.Ticker('TRENT.NS')

In [11]:
trent.info

{'address1': 'Trent House, G-Block',
 'address2': 'Plot No. C-60, Beside Citibank Bandra Kurla Complex Bandra (East)',
 'city': 'Mumbai',
 'zip': '400051',
 'country': 'India',
 'phone': '91 22 6700 9000',
 'fax': '91 22 6700 8100',
 'website': 'https://trentlimited.com',
 'industry': 'Apparel Retail',
 'industryKey': 'apparel-retail',
 'industryDisp': 'Apparel Retail',
 'sector': 'Consumer Cyclical',
 'sectorKey': 'consumer-cyclical',
 'sectorDisp': 'Consumer Cyclical',
 'longBusinessSummary': 'Trent Limited engages in the retailing and trading of apparels, footwear, accessories, toys, games, and other products in India. The company provides apparel, footwear, and accessories for men, women, and children, as well as furnishings, decor, and a range of home accessories under the Westside brand; apparels and footwear for men, women, and children under the Zudio brand; ethnic apparels, beauty products, and accessories under the Utsa brand; beauty products and accessories for girls under the Misbu brand; and luxurious occasion and ethnic wear for men and women under the Samoh brand. It also operates Star Hypermarket, a convenience store chain that offers a range of products, including staple foods, beverages, health and beauty products, apparel, home furnishings, vegetables, fruits, dairy and non-vegetarian products; and Booker Wholesale, a cash and carry chain of stores, which provides various products, such as staple foods, beverages, health and beauty products, dairy, non-vegetarian products, and non-food products to caterers, retailers, and other businesses. In addition, the company engages in the operation of StarQuik for online grocery retailing; provision of business support and outsourcing services relating to accounting, merchandising, human resources, payroll, etc.; and franchisee business. Further, it sells its products online through Westside.com, Tata CliQ, and Tata Neu. Trent Limited was incorporated in 1952 and is based in Mumbai, India.',
 'fullTimeEmployees': 25277,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Venkatesalu  Palaniswamy',
   'age': 46,
   'title': 'CEO & Executive Director',
   'yearBorn': 1977,
   'fiscalYear': 2024,
   'totalPay': 70900000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Neeraj  Basur ACA, ACS, M.Com',
   'age': 54,
   'title': 'Chief Financial Officer',
   'yearBorn': 1969,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. P. K. Anand',
   'age': 69,
   'title': 'Senior Vice-President of Operations',
   'yearBorn': 1954,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. S. W. Kamat',
   'age': 69,
   'title': 'General Manager of Finance & Accounts',
   'yearBorn': 1954,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Krupa Ketan Anandpara',
   'title': 'Company Secretary & Compliance Officer',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Manish  Kumar B.Sc., M.S.J.R., M.Sc., P.G.D.P.',
   'age': 55,
   'title': 'Head of Human Recourse',
   'yearBorn': 1968,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Sanjay  Rastogi',
   'age': 56,
   'title': 'Head - New Business, Strategy, CSR & ESG',
   'yearBorn': 1967,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Shailesh  Solkar',
   'title': 'Head of Merchandising & Supply Chain',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Damani  Madhulika',
   'title': 'Head of Indian Wear',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ratul  Neogi',
   'title': 'Head of Internal Audit & BR',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'compensationAsOfEpochDate': 1735603200,
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 7149.0,
 'open': 7109.0,
 'dayLow': 6950.0,
 'dayHigh': 7150.3,
 'regularMarketPreviousClose': 7149.0,
 'regularMarketOpen': 7109.0,
 'regularMarketDayLow': 6950.0,
 'regularMarketDayHigh': 7150.3,
 'dividendRate': 3.2,
 'dividendYield': 0.0004,
 'exDividendDate': 1716336000,
 'payoutRatio': 0.066700004,
 'fiveYearAvgDividendYield': 0.12,
 'beta': 0.438,
 'trailingPE': 147.90097,
 'forwardPE': 113.21927,
 'volume': 681648,
 'regularMarketVolume': 681648,
 'averageVolume': 1045321,
 'averageVolume10days': 482006,
 'averageDailyVolume10Day': 482006,
 'marketCap': 2514030952448,
 'fiftyTwoWeekLow': 2181.7,
 'fiftyTwoWeekHigh': 8345.0,
 'priceToSalesTrailing12Months': 18.150303,
 'fiftyDayAverage': 7462.869,
 'twoHundredDayAverage': 5376.55,
 'currency': 'INR',
 'enterpriseValue': 2518809837568,
 'profitMargins': 0.12316,
 'floatShares': 201223677,
 'sharesOutstanding': 355487008,
 'heldPercentInsiders': 0.43118998,
 'heldPercentInstitutions': 0.24108,
 'impliedSharesOutstanding': 355905984,
 'bookValue': 114.427,
 'priceToBook': 61.731495,
 'lastFiscalYearEnd': 1711843200,
 'nextFiscalYearEnd': 1743379200,
 'mostRecentQuarter': 1719705600,
 'earningsQuarterlyGrowth': 1.263,
 'netIncomeToCommon': 17058899968,
 'trailingEps': 47.76,
 'forwardEps': 62.39,
 'pegRatio': 3.15,
 'lastSplitFactor': '10:1',
 'lastSplitDate': 1473638400,
 'enterpriseToRevenue': 18.185,
 'enterpriseToEbitda': 147.939,
 '52WeekChange': 2.1919892,
 'SandP52WeekChange': 0.31214523,
 'lastDividendValue': 3.2,
 'lastDividendDate': 1716336000,
 'exchange': 'NSI',
 'quoteType': 'EQUITY',
 'symbol': 'TRENT.NS',
 'underlyingSymbol': 'TRENT.NS',
 'shortName': 'TRENT LTD',
 'longName': 'Trent Limited',
 'firstTradeDateEpochUtc': 1025495100,
 'timeZoneFullName': 'Asia/Kolkata',
 'timeZoneShortName': 'IST',
 'uuid': '2d4733f2-b83b-36d9-aadc-9c8dd3fde556',
 'messageBoardId': 'finmb_20376352',
 'gmtOffSetMilliseconds': 19800000,
 'currentPrice': 7063.75,
 'targetHighPrice': 5811.0,
 'targetLowPrice': 1730.0,
 'targetMeanPrice': 4322.58,
 'targetMedianPrice': 4600.0,
 'recommendationMean': 2.4,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 19,
 'totalCash': 10143200256,
 'totalCashPerShare': 28.533,
 'ebitda': 17025999872,
 'totalDebt': 17529899008,
 'totalRevenue': 138511794176,
 'debtToEquity': 42.729,
 'revenuePerShare': 389.612,
 'earningsGrowth': 1.262,
 'revenueGrowth': 0.562,
 'grossMargins': 0.42988,
 'ebitdaMargins': 0.12292,
 'operatingMargins': 0.105100006,
 'financialCurrency': 'INR',
 'trailingPegRatio': None}